### ISSUE TITLE
Aktivität erstellen

### ISSUE THREAD

**Issue by Reawel** [sweIhm/sweiproject-tg1a-4#13]
User Story|Beschreibung|Akzeptanzkriterien
---|---|---
Als angemeldeter Benutzer will ich eine Aktivität erstellen, um Studenten zu informieren und zu werben.|Angemeldete User sind sind fähig Veranstaltungen zu erstellen.|Nutzer muss registriert und angemeldet sein.

**Comment by Reawel** [comment]
Im Backend kann eine Aktivität erzeugt werden.
Mit der Methode/newAcitvity 
Values:
Title (erforderlich),
Description (erforderlich)
Category (erforderlich)
Tags (seperiert mit ',') (optional)

**Comment by Andreaslerc** [comment]
Klasse Activity ist fertig und in jpa eingebunden jede Aktivität besitzt eine ID die eine LONG ist. DIe ID starten mit 1, 2, 3, ..... also long 1L ....

**Comment by Reawel** [comment]
# Wichtig!
Es kann nur eine Aktivität erstellt werden wenn Category einer der folgenden Werte besitzt
Event("event"),
	```
Project("project"),
	Announcement("announcement"),
	Guide("guide"),
	News("news"),
	Article("article");
```
Wenn die Werte im Frontend nicht genau so angegeben werden, 
kommt es zu einer BadRequest!!

@Duciwuci Hierzu bitte ein neues Issue erstellen. Danke 👍

**Comment by Andreaslerc** [comment]
H2 geadded in application.properties die Daten von JPA werden jetzt in eine SQL Datenbank geschrieben
unter http://localhost:8080/h2 kann man es testen

**Comment by Andreaslerc** [comment]
getestet mit einem Travis.ci neustart. Die Aktivität bleibt auf der App
