### ISSUE TITLE
Aktivität bearbeiten

### ISSUE THREAD

**Issue by Reawel** [sweIhm/sweiproject-tg1a-4#8]
User Story|Beschreibung|Akzeptanzkriterien
---|---|---
Als angemeldeter Benutzer will ich meine Aktivität bearbeiten, um Details zu ändern.|Autoren können Informationen, Bilder und Beschreibungen ihrer eigenen Aktivität ändern.|Aktivität müssen existieren und User muss Autor sein.

**Comment by Andreaslerc** [comment]
To Do: neue Methode in Activity Controller erstellen : updateActivity
dann in MainController eine neue Methode dafür machen :)
