### ISSUE TITLE
Autor einer Aktivität kontaktieren

### ISSUE THREAD

**Issue by Reawel** [sweIhm/sweiproject-tg1a-4#9]
User Story|Beschreibung|Akzeptanzkriterien
---|---|---
Als angemeldeter Benutzer will ich den Autor kontaktieren, um detailliertere Informationen zu bekommen oder mit ihm über Informationen austauschen.|Der Autor hinterlässt seine Daten, um auf Fragen von anderen User zu antworten. |Aktivität muss existieren und der User muss registriert und angemeldet sein.

**Comment by Andreaslerc** [comment]
Es soll eine Methode in MainController geben die den Textinhalt und Titel bekommt und dann diesen Inhalt per Email an den Autor sendet.

**Comment by Andreaslerc** [comment]
Java braucht folgende Daten:  **Name des Absenders** , **Name des Autors**, **Betreff** , **Textinhalt**
